export const SPAWN_CONSTANTS = {
  // Spawn timing
  INITIAL_SPAWN_INTERVAL: 1000,
  MIN_SPAWN_INTERVAL: 300,
  SPAWN_INTERVAL_DECREASE: 50,

  // Spawn distances
  MIN_SPAWN_DISTANCE: 300,
  MAX_SPAWN_DISTANCE: 500,

  // Enemy limits
  MAX_ENEMIES: 3000,
  MIN_ENEMY_SPEED: 0.2,
  MAX_ENEMY_SPEED: 2,
  ENEMY_SPEED_INCREASE: 0.01,

  // Wave settings
  INITIAL_WAVE_DURATION: 1000,
  MIN_WAVE_DURATION: 1000,
  WAVE_DURATION_DECREASE: 1000,
  INITIAL_ENEMIES_PER_WAVE: 10,
  ENEMIES_PER_WAVE_INCREASE: 5,
  WAVE_ENEMY_MULTIPLIER: 1.25,
} as const;
