import {
  AIComponent,
  AnimationComponent,
  ChaseComponent,
  ColliderComponent,
  DamageComponent,
  DamageTextComponent,
  DeathMarkComponent,
  ExperienceComponent,
  HealthComponent,
  InputComponent,
  LifecycleComponent,
  MovementComponent,
  PickupComponent,
  RenderComponent,
  SoundEffectComponent,
  SpiralMovementComponent,
  StateComponent,
  StatsComponent,
  VelocityComponent,
  WeaponComponent,
} from '@ecs/components';
import { Component } from '../ecs/Component';
import { ComponentConstructor, EntityType } from '../ecs/types';

export const EntityPoolList: EntityType[] = [
  'player',
  'enemy',
  'projectile',
  'weapon',
  'areaEffect',
  'damageText',
  'pickup',
  'effect',
  'other',
];

export const ComponentPoolList: ComponentConstructor<Component>[] = [
  MovementComponent,
  RenderComponent,
  HealthComponent,
  AIComponent,
  ColliderComponent,
  VelocityComponent,
  DamageComponent,
  LifecycleComponent,
  InputComponent,
  ExperienceComponent,
  StatsComponent,
  WeaponComponent,
  PickupComponent,
  DamageTextComponent,
  DeathMarkComponent,
  ChaseComponent,
  SoundEffectComponent,
  SpiralMovementComponent,
  StateComponent,
  AnimationComponent,
];
